import { Inter } from "next/font/google"
import { Toaster } from "react-hot-toast"
import { ContextProvider } from "../providers/ContextProvider"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Trading App",
	description: "Generated by create next app"
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<ContextProvider>
				<body className={inter.className}>
					<Toaster />
					{children}
				</body>
			</ContextProvider>
		</html>
	)
}
